# Generated by Django 5.1.6 on 2025-03-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial_categories'),
        ('api', '0004_recipe_image'),
    ]

    operations = [
    ]
